// eslint-disable-next-line import/prefer-default-export
export const siteList = [
  {
    siteCode: "630",
    siteIcon: "/images/shop_logos/logo0630.gif",
    siteName: "라쿠텐",
    shopName: "라쿠텐테스트",
    autoTemplateId: 61,
    manualTemplateId: 241,
  },
  {
    siteCode: "910",
    siteIcon: "/images/shop_logos/logo0910.gif",
    siteName: "Qoo10",
    shopName: "노현석Qoo10",
    autoTemplateId: 89,
    manualTemplateId: 269,
  },
  {
    siteCode: "1000",
    siteIcon: "/images/shop_logos/kakao_present.png",
    siteName: "카카오선물하기",
    shopName: "영화_카카오선물하기",
    autoTemplateId: 97,
    manualTemplateId: 277,
  },
  {
    siteCode: "1050",
    siteIcon: "/images/shop_logos/blogpay.png",
    siteName: "블로그페이",
    shopName: "김성찬_블로그_페이",
    autoTemplateId: 102,
    manualTemplateId: 282,
  },
  {
    siteCode: "1070",
    siteIcon: "/images/shop_logos/29cm.png",
    siteName: "29cm",
    shopName: "29cm",
    autoTemplateId: 104,
    manualTemplateId: 284,
  },
  {
    siteCode: "1200",
    siteIcon: "/images/shop_logos/womanstalk.gif",
    siteName: "우먼스톡",
    shopName: "사방넷 테스트",
    autoTemplateId: 117,
    manualTemplateId: 297,
  },
  {
    siteCode: "1660",
    siteIcon: "/images/shop_logos/logo1660.png",
    siteName: "아임웹",
    shopName: "플레이 오토 테스트",
    autoTemplateId: 163,
    manualTemplateId: 343,
  },
  {
    siteCode: "1680",
    siteIcon: "/images/shop_logos/logo1680.gif",
    siteName: "롯데온",
    shopName: "롯데온",
    autoTemplateId: 165,
    manualTemplateId: 345,
  },
  {
    siteCode: "1730",
    siteIcon: "/images/shop_logos/logo1730.png",
    siteName: "위메프API",
    shopName: "위메프api",
    autoTemplateId: 168,
    manualTemplateId: 348,
  },
  {
    siteCode: "1740",
    siteIcon: "/images/shop_logos/logo1740.png",
    siteName: "쿠팡API",
    shopName: "쿠팡API",
    autoTemplateId: 169,
    manualTemplateId: 349,
  },
  {
    siteCode: "1750",
    siteIcon: "/images/shop_logos/logo1700.png",
    siteName: "롯데홈쇼핑API",
    shopName: "영화_롯데홈쇼핑API",
    autoTemplateId: 170,
    manualTemplateId: 350,
  },
  {
    siteCode: "1760",
    siteIcon: "/images/shop_logos/logo1760.png",
    siteName: "카페24Api3.0",
    shopName: "카페24Api3.0",
    autoTemplateId: 171,
    manualTemplateId: 351,
  },
  {
    siteCode: "1780",
    siteIcon: "/images/shop_logos/logo1780.png",
    siteName: "스타일쉐어",
    shopName: "스타일쉐어",
    autoTemplateId: 173,
    manualTemplateId: 353,
  },
  {
    siteCode: "1790",
    siteIcon: "/images/shop_logos/ESMAPI.png",
    siteName: "ESM API",
    shopName: "esm",
    autoTemplateId: 174,
    manualTemplateId: 354,
  },
  {
    siteCode: "1840",
    siteIcon: "/images/shop_logos/logo1840.png",
    siteName: "하이버",
    shopName: "하이버_gentlebig",
    autoTemplateId: 178,
    manualTemplateId: 358,
  },
];

export const templateList = [
  {
    id: '1',
    site_code: '1',
    template_name: '기본',
    create_at: '2021-08-01 14:02:59',
    update_at: null,
    deleted_at: null,
  },
  {
    id: '2',
    site_code: '1',
    template_name: 'test',
    create_at: '2021-08-11 14:05:02',
    update_at: null,
    deleted_at: null,
  },
  {
    id: '3',
    site_code: '1',
    template_name: '수정된 양식',
    create_at: '2021-08-11 14:05:02',
    update_at: null,
    deleted_at: null,
  },
  {
    id: '4',
    site_code: '1',
    template_name: '템플릿 샘플',
    create_at: '2021-08-11 14:05:02',
    update_at: null,
    deleted_at: null,
  },
];

export const orderDataArray = [
  {
    label: '주문',
    value: 'orders',
    mComments: '주문과 관련된 항목에 대해 선택해주세요.',
    aComments: '주문과 관련된 항목에 대해 입력해주세요.',
    sub: [
      {
        subTitle: '판매처 주문번호',
        subCaption: '판매처가 지정한 주문 단위별 고유한 주문번호',
        separateOpts: false,
        value: 'code',
        required: true,
        immutable: true,
      },
      {
        subTitle: 'SEQ코드',
        subCaption:
          '판매처가 지정한 품목 단위별 고유한 주문번호. 미존재시 주문순번(Sequence code)',
        separateOpts: false,
        value: 'items.code',
        immutable: true,
        required: true,
      },
      {
        subTitle: '협력사 번호',
        subCaption: '협력사의 번호. 단순 확인용으로 없는 경우 비워두세요.',
        separateOpts: false,
        value: 'partnerCode',
      },
      {
        subTitle: '상점번호',
        subCaption: '판매처의 상점번호. 단순 확인용으로 없는 경우 비워두세요.',
        separateOpts: false,
        value: 'shopCode',
      },
      {
        subTitle: '주문자',
        subCaption: '주문한 사람의 이름',
        separateOpts: false,
        value: 'orderer',
      },
      {
        subTitle: '주문자 전화번호',
        subCaption: '주문자의 전화번호',
        separateOpts: false,
        value: 'ordererTelephone',
      },
      {
        subTitle: '주문자 휴대폰번호',
        subCaption: '주문자의 휴대폰 번호',
        separateOpts: false,
        value: 'ordererMobile',
      },
      {
        subTitle: '주문자 아이디',
        subCaption: '주문자의 아이디',
        separateOpts: false,
        value: 'ordererId',
      },
    ],
  },
  {
    label: '상품',
    value: 'products',
    mComments: '상품과 관련된 항목에 대해 선택해주세요.',
    aComments: '상품과 관련된 항목에 대해 입력해주세요.',
    sub: [
      {
        subTitle: '판매처 상품명',
        subCaption: '판매처의 상품 이름',
        separateOpts: false,
        value: 'items.productName',
      },
      {
        subTitle: '판매처 상품코드',
        subCaption: '판매처의 상품 식별 코드',
        separateOpts: false,
        value: 'items.productCode',
      },
      {
        subTitle: '주문 일자',
        subCaption: '상품을 주문한 일자',
        separateOpts: false,
        value: 'realOrderedAt',
      },
      {
        subTitle: '상품옵션1',
        subCaption: '해당 상품의 크기나 색상 등의 옵션',
        separateOpts: false,
        value: 'items.productVariantName',
      },
      {
        subTitle: '상품옵션2',
        subCaption: '해당 상품의 크기나 색상 등의 옵션',
        separateOpts: false,
        value: 'items.productVariantName2',
      },
      {
        subTitle: '상품옵션3',
        subCaption: '해당 상품의 크기나 색상 등의 옵션',
        separateOpts: false,
        value: 'items.productVariantName3',
      },
      {
        subTitle: '상세 요구사항',
        subCaption: '구매자의 상세요구사항, 배송메세지 등을 말함.',
        separateOpts: false,
        value: 'additionalRequirements',
      },
      {
        subTitle: '공급가',
        subCaption: '상품의 원가. 단순 확인용으로 없는 경우 비워두세요.',
        separateOpts: false,
        value: 'items.supplyPrice',
      },
      {
        subTitle: '수량',
        subCaption: '상품 구매 개수',
        separateOpts: false,
        value: 'items.qty',
      },
      {
        subTitle: '금액',
        subCaption:
          '상품별 구매 금액, 금액 입력란은 수식을 사용할 수 있습니다.',
        precautions: 'eg. price=unitPrice*qty (금액=단가*수량)',
        icon: true,
        separateOpts: false,
        input: true,
        value: 'items.price',
      },
    ],
  },
  {
    label: '배송',
    value: 'deliveries',
    mComments: '배송과 관련된 항목에 대해 선택해주세요.',
    aComments: '배송과 관련된 항목에 대해 입력해주세요.',
    sub: [
      {
        subTitle: '수령자',
        subCaption: '받는 사람의 이름',
        separateOpts: false,
        value: 'receiver',
      },
      {
        subTitle: '전화번호',
        subCaption: '수령자의 전화번호',
        separateOpts: false,
        value: 'receiverTelephone',
      },
      {
        subTitle: '휴대폰번호',
        subCaption: '수령자의 수령자 번호',
        separateOpts: false,
        value: 'receiverMobile',
      },
      {
        subTitle: '우편번호',
        subCaption:
          '송장 출력 및 발송을 위한 행정구역 기준으로 부여한 우편번호',
        precautions:
          '셀메이트 내 송장출력 기능을 사용하려면 우편번호를 필수로 입력해야 합니다.',
        separateOpts: false,
        icon: true,
        value: 'postcode',
      },
      {
        subTitle: '주소',
        subCaption: '받는 사람의 기본주소',
        separateOpts: false,
        value: 'address',
      },
      {
        subTitle: '주소2',
        subCaption:
          '받는 사람의 상세주소. 주소(기본주소)에 전체주소 포함되는 경우 비워두세요.',
        separateOpts: false,
        value: 'detailedAddress',
      },
      {
        subTitle: '송장번호',
        subCaption: '상품의 송장번호',
        separateOpts: false,
        value: 'invoiceNo',
      },
      {
        subTitle: '배송비',
        subCaption: '상품의 배송비',
        separateOpts: false,
        value: 'shippingFee',
      },
      {
        subTitle: '선착불 파라미터',
        subCaption: '배송비에 대한 선불, 착불 파라미터 지정',
        separateOpts: true,
        value: 'rawDeliveryPaymentMethod',
      },
      {
        conditionTitle: '착불 조건 설정',
        conditionCaption: [
          '착불 문자열은 반드시 ""로 감싸야 합니다.',
          '선후불 파라미터 값이 착불 문자열에 포함된다면 착불, 포함되지 않는다면 선불로 처리됩니다.',
          '"무조건착불" 을 입력시 모든 주문이 착불로 처리됩니다.',
          '착불문자열을설정하지 않으면 모든 주문이 선불로 처리됩니다.',
        ],
        condition: true,
        value: 'payOnDeliveryStr',
      },
      {
        subTitle: '사용자정의1(결제 일시)',
        subCaption: '상품 주문 후 결제일시',
        precautions:
        '없는 경우 비워두세요. 다른 정보 설정시 재고할당에 문제될 수 있습니다.',
        icon: true,
        separateOpts: false,
        value: 'items.userDefine1',
      },
    ],
  },
  {
    label: '기타',
    value: 'others',
    mComments: '사용자 정의와 관련된 항목에 대해 선택해주세요.',
    aComments: '사용자 정의와 관련된 항목에 대해 입력해주세요.',
    sub: [
      {
        subTitle: '사용자정의2',
        subCaption: '기타정보. 자유롭게 수집 원하는 정보를 설정합니다.',
        separateOpts: false,
        value: 'items.userDefine2',
      },
      {
        subTitle: '사용자정의3',
        subCaption: '기타정보. 자유롭게 수집 원하는 정보를 설정합니다.',
        separateOpts: false,
        value: 'items.userDefine3',
      },
      {
        subTitle: '사용자정의4',
        subCaption: '기타정보. 자유롭게 수집 원하는 정보를 설정합니다.',
        separateOpts: false,
        value: 'items.userDefine4',
      },
      {
        subTitle: '사용자정의5',
        subCaption: '기타정보. 자유롭게 수집 원하는 정보를 설정합니다.',
        separateOpts: false,
        value: 'items.userDefine5',
      },
      {
        subTitle: '사용자정의6',
        subCaption: '기타정보. 자유롭게 수집 원하는 정보를 설정합니다.',
        separateOpts: false,
        value: 'items.userDefine6',
      },
      {
        subTitle: '사용자정의7',
        subCaption: '기타정보. 자유롭게 수집 원하는 정보를 설정합니다.',
        separateOpts: false,
        value: 'items.userDefine7',
      },
      {
        subTitle: '사용자정의8',
        subCaption: '기타정보. 자유롭게 수집 원하는 정보를 설정합니다.',
        separateOpts: false,
        value: 'items.userDefine8',
      },
      {
        subTitle: '사용자정의9',
        subCaption: '기타정보. 자유롭게 수집 원하는 정보를 설정합니다.',
        separateOpts: false,
        value: 'items.userDefine9',
      },
      {
        subTitle: '사용자정의10',
        subCaption: '기타정보. 자유롭게 수집 원하는 정보를 설정합니다.',
        separateOpts: false,
        value: 'items.userDefine10',
      },
    ],
  },
  {
    label: '해외',
    value: 'overseas',
    mComments: '해외와 관련된 항목에 대해 선택해주세요.',
    aComments: '해외와 관련된 항목에 대해 입력해주세요.',
    sub: [
      {
        subTitle: '영문상품명',
        separateOpts: false,
        value: 'items.intlProductName',
      },
      {
        subTitle: '국가상품명',
        separateOpts: false,
        value: 'items.intlCrProductName',
      },
      {
        subTitle: '해외URL',
        separateOpts: false,
        value: 'items.intlUrl',
      },
      {
        subTitle: '구매금액',
        separateOpts: false,
        value: 'items.intlPurchasePrice',
      },
      {
        subTitle: '상품혼용률',
        separateOpts: false,
        value: 'items.intlMixingRatio',
      },
      {
        subTitle: '옷감',
        separateOpts: false,
        value: 'items.intlFabric',
      },
      {
        subTitle: 'HS CODE',
        separateOpts: false,
        value: 'items.intlHsCode',
      },
      {
        subTitle: '영문수령자명',
        separateOpts: false,
        value: 'intlReceiver',
      },
      {
        subTitle: '영문성(Last Name)',
        separateOpts: false,
        value: 'intlReceiverLastName',
      },
      {
        subTitle: '영문이름(First Name)',
        separateOpts: false,
        value: 'intlReceiverFirstName',
      },
      {
        subTitle: '이메일',
        separateOpts: false,
        value: 'intlReceiverEmail',
      },
      {
        subTitle: '우편번호',
        separateOpts: false,
        value: 'intlPostcode',
      },
      {
        subTitle: '영문주소1',
        separateOpts: false,
        value: 'intlAddress1',
      },
      {
        subTitle: '영문주소2',
        separateOpts: false,
        value: 'intlAddress2',
      },
      {
        subTitle: '영문주소3',
        separateOpts: false,
        value: 'intlAddress3',
      },
      {
        subTitle: '국가코드',
        separateOpts: false,
        value: 'intlCountryCode',
      },
      {
        subTitle: '국가명',
        separateOpts: false,
        value: 'intlCountry',
      },
      {
        subTitle: 'state',
        separateOpts: false,
        value: 'intlState',
      },
      {
        subTitle: 'city',
        separateOpts: false,
        value: 'intlCity',
      },
      {
        subTitle: '국가통화',
        separateOpts: false,
        value: 'intlCurrency',
      },
    ],
  },
];
